######################################################################
# Automatically generated by qmake (2.01a) sam. mars 24 23:44:07 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += network

# Input
HEADERS += server.hpp
SOURCES += main.cpp server.cpp
