######################################################################
# Automatically generated by qmake (2.01a) Thu Feb 23 18:28:46 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += client.hpp webcammanager.hpp
FORMS += client.ui
SOURCES += client.cpp main.cpp webcammanager.cpp
