######################################################################
# Automatically generated by qmake (2.01a) Fri Feb 24 00:35:01 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += client.hpp webcammanager.hpp widgetwebcam.hpp
FORMS += client.ui
SOURCES += client.cpp main.cpp webcammanager.cpp widgetwebcam.cpp
