######################################################################
# Automatically generated by qmake (2.01a) dim. mars 25 13:22:56 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += network

# Input
HEADERS += server.hpp servergraphics.hpp
SOURCES += main.cpp server.cpp servergraphics.cpp
