######################################################################
# Automatically generated by qmake (2.01a) lun. mars 26 22:14:18 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += network

# Input
HEADERS += packagemanager.hpp server.hpp servergraphics.hpp
SOURCES += main.cpp packagemanager.cpp server.cpp servergraphics.cpp
